assets/scss/lol.scss
content/guest-essays/buddhism-and-utilitarianism.md
content/guest-essays/naturalistic-arguments-for-ethical-hedonism.md
content/guest-essays/utilitarianism-and-nonhuman-animals.md
content/guest-essays/virtues-for-real-world-utilitarians.md
content/peter-singer-famine-affluence-and-morality.md
layouts/shortcodes/button.html
layouts/shortcodes/two-button.html

two-button banner

---

content/utilitarian-quotes.md
layouts/partials/site-navigation-2.html

Utilitarian Quotes Page

---

assets/scss/lol.scss
content/_index.md
content/guest-essays/_index.md
layouts/index.html
layouts/partials/site-footer.html
layouts/shortcodes/index-navigation.html
layouts/shortcodes/small-button.html

👍 styled and all links added 😎

Homepage & footer

---

assets/scss/lol.scss
content/books/_index.html
content/books/autobiography-john-stuart-mill/1.md
content/books/autobiography-john-stuart-mill/2.md
content/books/autobiography-john-stuart-mill/3.md
content/books/autobiography-john-stuart-mill/4.md
content/books/autobiography-john-stuart-mill/5.md
content/books/autobiography-john-stuart-mill/6.md
content/books/autobiography-john-stuart-mill/7.md
content/books/enfranchisement-of-women-harriet-taylor-mill.md
content/books/on-liberty-john-stuart-mill/1.md
content/books/on-liberty-john-stuart-mill/2.md
content/books/on-liberty-john-stuart-mill/3.md
content/books/on-liberty-john-stuart-mill/4.md
content/books/on-liberty-john-stuart-mill/5.md
content/books/the-subjection-of-women-john-stuart-mill/1.md
content/books/the-subjection-of-women-john-stuart-mill/2.md
content/books/the-subjection-of-women-john-stuart-mill/3.md
content/books/the-subjection-of-women-john-stuart-mill/4.md
content/books/utilitarianism-john-stuart-mill/1.md
content/books/utilitarianism-john-stuart-mill/2.md
content/books/utilitarianism-john-stuart-mill/3.md
content/books/utilitarianism-john-stuart-mill/4.md
content/books/utilitarianism-john-stuart-mill/5.md
layouts/_default/book.html
layouts/shortcodes/book-navigation.html

😎 `{{< book-TOC >}}` book table of contents programmatically generated based on the `menu` _frontmatter_ property 👍

Book Table of Contents

---

assets/scss/lol.scss
layouts/partials/site-navigation.html

Active class on menu dropdown

---

content/guest-essays/bentham-and-criminal-law.md
content/guest-essays/buddhism-and-utilitarianism.md
content/guest-essays/naturalistic-arguments-for-ethical-hedonism.md
content/guest-essays/precis-of-the-feeling-of-value.md
content/guest-essays/utilitarianism-and-nonhuman-animals.md
content/guest-essays/virtues-for-real-world-utilitarians.md

Guest essays have nice header

---

assets/scss/lol.scss
content/_index.md
layouts/shortcodes/all-thinkers.html

Styling improvements

---

assets/scss/buttons.scss
assets/scss/colors.scss
assets/scss/developer-mode.scss
assets/scss/font.scss
assets/scss/footer.scss
assets/scss/footnotes.scss
assets/scss/glossary.scss
assets/scss/header.scss
assets/scss/homepage.scss
assets/scss/lol.scss
assets/scss/thinkers.scss
assets/scss/toc.scss
content/_index.md
content/glossary.md
content/resources-and-further-reading.md
layouts/_default/baseof.html
layouts/partials/footnotes-script.html
layouts/partials/head-extra.html
layouts/partials/head.html
layouts/shortcodes/guest-essays.html

😓  not `mobile-ready` as the branch name would suggest - but it's a good polish-up of what I had before 👍 😭 👍

Split SCSS & set colors as variables

---

README.md
assets/scss/glossary.scss
assets/scss/header.scss
assets/scss/lol.scss
assets/scss/mobile.scss
assets/scss/mobilenav.scss
assets/scss/unsorted.scss
content/textbook.md
layouts/_default/baseof.html
layouts/partials/page-header.html
layouts/shortcodes/textbook-contents.html

Mobile navigation

---

content/glossary.md

Glossary cleanup

---

config.toml

Google analytics GA4 tag added

---

content/guest-essays/bentham-and-criminal-law.md
content/guest-essays/buddhism-and-utilitarianism.md
content/guest-essays/naturalistic-arguments-for-ethical-hedonism.md
content/guest-essays/precis-of-the-feeling-of-value.md
content/guest-essays/utilitarianism-and-nonhuman-animals.md
content/guest-essays/utilitarianism-and-research-ethics.md
content/guest-essays/virtues-for-real-world-utilitarians.md
layouts/shortcodes/essay-author.html

About the authors is same size as h2

---

assets/scss/mobile.scss

chapter headings no error on mobile

---

assets/scss/unsorted.scss
content/about.md
content/utilitarian-thinkers.md
layouts/page/single.html
layouts/shortcodes/endorsement.html
layouts/shortcodes/read-more.html
layouts/shortcodes/thinker-wrapper.html
layouts/shortcodes/thinker.html

🤔 thinker page 😉 formatted like guest essays 😎 
Had to remove all links and footnotes from inside descriptions because it fouls up styling (and is "illegal" to have a link tag nested inside another link tag)

Thinker page rework

---

content/utilitarianism-for-high-school-students.md

For the article "Simply Explained"
✅ there were no import errors and I manually confirmed formatting and heading numbering / table of contents / etc
Please glance over, but there is no need to be thorough 👌

Fresh import from Google Docs

---

README.md
justfile
package.json

🚀  _dev_ environment setup is now super simple 😎

just is installed with npm

---

.gitignore
README.md
archive/README.md
build.js
justfile
package.json

zip finished build into single file

---

assets/scss/mobile.scss
assets/scss/thinkers.scss
content/about.md
content/acting-on-utilitarianism.md
content/guest-essays/utilitarianism-and-climate-change.md
content/textbook.md
justfile
layouts/shortcodes/endorsement.html
layouts/shortcodes/essay-author.html

Finishing touches

---

assets/scss/footer.scss
assets/scss/mobile.scss
layouts/partials/site-footer.html

Mostly footer cleanup 🧹 
Styling a bit better 😅

Misc stuff

---

assets/scss/mobilenav.scss
layouts/_default/baseof.html
layouts/partials/func/style/GetMainCSS.html
layouts/partials/head.html
layouts/robots.txt

cleaning up files for clarity 😊 
*Update* - `robots.txt` to exclude the search index folder `_pagefind` ✅

Remove unused

---

.gitmodules
README.md
assets/scss/unsorted.scss
config.toml
instructions/README.md
justfile
layouts/_default/baseof.html

🙇  thank you to [theme/ananke](https://github.com/theNewDynamic/gohugo-theme-ananke) for helping set up this project 🎉 
Many of the `/layouts` pages came from the theme and were then heavily edited. 
Now there is no longer a need for the _theme_ 🤝

remove theme

---

README.md
assets/scss/search.scss
instructions/README.md
package.json

🙌  Huge thank you to @bglw for implementing `Esc`-keypress-to-exit the search 🚀 
Really lovely feature to have in a search box ❤️ 
https://github.com/CloudCannon/pagefind/releases/tag/v0.11.0
🙇 https://github.com/CloudCannon/pagefind/issues/124
🙇 https://github.com/CloudCannon/pagefind/issues/44

Pagefind closes when Esc key pressed

---

assets/scss/bookpdf.scss
pdf/book.md

Bookmaking

---

content/objections-to-utilitarianism/_index.md
content/objections-to-utilitarianism/abusability.md
content/objections-to-utilitarianism/cluelessness.md
content/objections-to-utilitarianism/equality.md
content/resources-and-further-reading.md
layouts/partials/objections.html
layouts/partials/site-footer.html
pdf/build-book.js

Add Cluelessness & Abusability objections

---

config.toml
content/acting-on-utilitarianism.es.md
content/arguments-for-utilitarianism.es.md
content/introduction-to-utilitarianism.es.md
content/near-utilitarian-alternatives.es.md
content/objections-to-utilitarianism/_index.es.md
content/objections-to-utilitarianism/abusability.es.md
content/objections-to-utilitarianism/alienation.es.md
content/objections-to-utilitarianism/cluelessness.es.md
content/objections-to-utilitarianism/demandingness.es.md
content/objections-to-utilitarianism/equality.es.md
content/objections-to-utilitarianism/mere-means.es.md
content/objections-to-utilitarianism/rights.es.md
content/objections-to-utilitarianism/separateness-of-persons.es.md
content/objections-to-utilitarianism/special-obligations.es.md
content/population-ethics.es.md
content/theories-of-wellbeing.es.md
content/types-of-utilitarianism.es.md
content/utilitarianism-and-practical-ethics.es.md

Thank you to @tlon-team for the translations 🙇‍♂️ 
https://github.com/tlon-team/utilitarianism-es

Spanish Translation

---

instructions/README.md

Some more tweaking needed for languages to work 100%, but this is a good start 👍

Languages instructions

---

archetypes/default.md
archive/site-navigation-2.html
content/de/_index.md
content/de/about.md
content/de/peter-singer-famine-affluence-and-morality.md
content/en/about.md
content/en/peter-singer-famine-affluence-and-morality.md
i18n/de.toml
i18n/en-US.toml
i18n/en.toml
i18n/es.toml
layouts/partials/site-footer.html
layouts/partials/site-navigation-2.html
layouts/shortcodes/index-navigation.html

- Menu has translated strings
- Menu looks different when language is `de` (excludes missing links)

Menu & links translated

---

content/de/09-resources-and-further-reading.md
i18n/de.toml
i18n/en.toml
i18n/es.toml
layouts/partials/page-header.html
layouts/partials/site-footer.html
layouts/partials/site-navigation-2.html
layouts/shortcodes/index-navigation.html

mobile links correct

---

config.toml
package.json

bump all versions to March 2024 latest

---

assets/scss/buttons.scss
content/de/09-resources-and-further-reading.md
i18n/de.toml
layouts/shortcodes/how-to-cite.html

😅  took so long 😓 but we're done now 🥳

Finish German translation

---

README.md
instructions/README.md
instructions/translating.md

🚀  to make future translations easier and faster to release 🚀

i18n / translation instructions

---

README.md
instructions/README.md

clean up readme

---

i18n/es.toml

Getting ready to publish the Spanish translation of the website 🥳

Utilitarismo

---

i18n/de.toml
i18n/en.toml
i18n/es.toml
layouts/partials/PDF.html

download as PDF translated

---

content/es/_index.md
content/es/about.md
content/es/textbook.md

This commit improves the Spanish translations of the three files we translated recently.

Improve Spanish translations

---

README.md
assets/scss/unsorted.scss
instructions/README.md
layouts/partials/head-extra.html
package.json

👍 update to newest version
✅ confirmed website still builds correctly 🥳

Hugo 0.134.0

---

layouts/partials/site-footer.html

Thank you @benthamite for the recommendation! Can help with SEO for our translated pages 🥳🤞

link to Spanish and German translations in the footer

---

.vscode/extensions.json
assets/scss/book.scss
assets/scss/header.scss
assets/scss/homepage.scss
assets/scss/mobile.scss
assets/scss/unsorted.scss
content/en/_index.md
content/en/about.md
content/en/textbook.md
content/en/utilitarian-quotes.md
i18n/en.toml
layouts/_default/baseof.html
layouts/page/single.html
layouts/partials/footnotes-script.html
layouts/partials/head-extra.html
layouts/partials/page-header.html
layouts/shortcodes/index-navigation.html

Thank you Richard for all the fixes prior to this 🤝 
Opening PR for a quick preview link 👍

homepage redesign - display book prominently
